name: Deploy
on:
  push:
    branches: ssg
  pull_request:
    branches: ssg

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build step
        run: "deno task build" # 📝 Update the build command(s) if necessary

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "existence"
          entrypoint: "https://deno.land/std@0.218.0/http/file_server.ts" # 📝 Update the entrypoint if necessary
          root: "./public" # 📝 Update the root if necessary
